apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: romanzhula/product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/config/
          volumeMounts:
            - name: config-volume
              mountPath: /config/
              readOnly: true
          envFrom:
            - secretRef:
                name: product-db-secret
      volumes:
        - name: config-volume
          configMap:
            name: product-service-config
