spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sep_user_db
    username: postgres
    password: YOUR_PASSWORD

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset-1.sql

server:
  port: 8081