spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://user-postgres-service:5432/sep_user_db
    username: postgres
    password: YOUR_PASSWORD

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        auto-time-requests: true

server:
  port: 8081
  address: 0.0.0.0

jwt:
  secret: "WzBZlEhw7iAX8Xe31wU4mzhrLWoSZL92JMWP+0CwLMm0Wtdkcye1zzH9Tp9a+nLwvAfLmZiVwt+k+Y3RObLrAA=="

logging:
  level:
    org:
      springframework:
        security: DEBUG