apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  application.yml: |
    spring:
      application:
        name: payment-service
      datasource:
        url: jdbc:postgresql://payment-postgres-service:5432/sep_payment_db
        username: postgres
        password: YOUR_PASSWORD
      flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
      kafka:
        bootstrap-servers: kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
    stripe:
      secret:
        key: sk_test_51N7tu0I3vHGJzoz7...xxxxxxx
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
          base-path: /actuator
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
        distribution:
          percentiles-histogram:
            http.server.requests: true
        web:
          server:
            auto-time-requests: true
    
    server:
      port: 8087
      address: 0.0.0.0