apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
data:
  application.yml: |
    spring:
      application:
        name: recommendation-service
      datasource:
        url: jdbc:postgresql://recommendation-db:5432/sep_recommendation_db
        username: postgres
        password: YOUR_PASSWORD
        driver-class-name: org.postgresql.Driver
      flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        bootstrap-servers: kafka:9092
        consumer:
          group-id: recommendation-service-group
          auto-offset-reset: earliest
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
    server:
      port: 8085
