version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=sep_product_db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_LISTENER_NAMES=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=1
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  product-service:
    image: romanzhula/product-service:latest
    container_name: product-service
    depends_on:
      - mongodb
      - redis
      - kafka
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/sep_product_db
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9093
    ports:
      - "8082:8082"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
