apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: romanzhula/payment-service:latest
          ports:
            - containerPort: 8087
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: application.yml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: payment-service-config