apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['order-service:8083']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'order-service:8083'

      - job_name: 'inventory-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['inventory-service:8084']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'inventory-service:8084'

      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-service:8086']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'notification-service:8086'

      - job_name: 'payment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['payment-service:8087']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'payment-service:8087'

      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-service:8082']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'product-service:8082'

      - job_name: 'recommendation-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['recommendation-service:8085']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'recommendation-service:8085'

      - job_name: 'user-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8081']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'user-service:8081'