spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/sep_product_db
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8082