spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/sep_product_db

  cache:
    type: redis
  redis:
    time-to-live: 1800000  # 30 min (30 * 60 * 1000)
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mongock:
  enabled: true
  migration-scan-package:
    - org.romanzhula.product_service.migrations

server:
  port: 8082