spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/sep_product_db

  cache:
    type: redis
  redis:
    time-to-live: 1800000  # 30 min (30 * 60 * 1000)
    host: localhost
    port: 6379

server:
  port: 8082