spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/sep_product_db

  cache:
    type: redis
  redis:
    time-to-live: 1800000  # 30 min (30 * 60 * 1000)
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: kafka:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
    web:
      server:
        auto-time-requests: true

mongock:
  enabled: true
  migration-scan-package:
    - org.romanzhula.product_service.migrations

server:
  port: 8082
  address: 0.0.0.0