apiVersion: v1
kind: Service
metadata:
  name: recommendation-postgres-service
spec:
  selector:
    app: recommendation-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP