apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: romanzhula/inventory-service:latest
          ports:
            - containerPort: 8084
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: application.yml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: inventory-service-config