apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
    release: prometheus
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP