apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: order-service
    release: prometheus
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP