spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  mail:
    host: smtp.ukr.net
    port: 2525
    username: YOUR_EMAIL
    password: YOUR_PASSWORD
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.ukr.net
        debug: true

server:
  port: 8086