# .github/workflows/cd-prod.yml

name: CD Production Pipeline

on:
  workflow_dispatch:

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_PROD }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy services to Production
        run: |
          chmod +x ./deploy-all.sh
          ./deploy-all.sh

      - name: Verify deployments
        run: |
          kubectl rollout status deployment/inventory-service --timeout=120s
          kubectl rollout status deployment/notification-service --timeout=120s
          kubectl rollout status deployment/order-service --timeout=120s
          kubectl rollout status deployment/payment-service --timeout=120s
          kubectl rollout status deployment/product-service --timeout=120s
          kubectl rollout status deployment/recommendation-service --timeout=120s
          kubectl rollout status deployment/user-service --timeout=120s

      - name: Finish
        run: echo "Production deployment completed successfully!"
